version: "3"

services:
  postgresql:
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    image: postgres:9.6
    networks:
      - temporal-network
    volumes:
      - "temporalpgdata:/var/lib/postgresql/data"
  temporal:
    depends_on:
      - postgresql
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
    image: temporalio/auto-setup:1.9.2
    networks:
      - temporal-network
    ports:
      - 7233:7233
    volumes:
      - ./config/temporal:/etc/temporal/config/dynamicconfig
  temporal-admin-tools:
    depends_on:
      - temporal
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:1.9.2
    networks:
      - temporal-network
    stdin_open: true
    tty: true
  temporal-web:
    depends_on:
      - temporal
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
      - TEMPORAL_PERMIT_WRITE_API=true
    image: temporalio/web:1.9.2
    networks:
      - temporal-network
    ports:
      - 8088:8088

volumes:
  temporalpgdata: {}

networks:
  temporal-network:
    driver: bridge
